In [1]:
import numpy as np

In [2]:
#Definición de un rango inicia en cero y termina en el valor -1
array = np.arange(5)

In [3]:
array

array([0, 1, 2, 3, 4])

In [4]:
#Innicio - fin
array = np.arange(2,10)

In [5]:
array

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Innicio - fin - aumento
array = np.arange(2,10,2)

In [7]:
array

array([2, 4, 6, 8])

In [8]:
#Crear un aray con cero 

np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
#Crear un aray con uni 

np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
#Genera numero entre un rango inicial y final

np.linspace(5,20,20)

array([ 5.        ,  5.78947368,  6.57894737,  7.36842105,  8.15789474,
        8.94736842,  9.73684211, 10.52631579, 11.31578947, 12.10526316,
       12.89473684, 13.68421053, 14.47368421, 15.26315789, 16.05263158,
       16.84210526, 17.63157895, 18.42105263, 19.21052632, 20.        ])

In [15]:
#Genera filas y columnas
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])