In [1]:
import numpy as np

In [3]:
np.random.rand(5)

array([0.78892189, 0.59560505, 0.02308628, 0.92537288, 0.38028925])

In [4]:
np.random.rand(5, 3)

array([[0.95146481, 0.04273758, 0.88368025],
       [0.03255846, 0.05520786, 0.27680393],
       [0.69912871, 0.03200318, 0.02322781],
       [0.14397684, 0.0539674 , 0.43240184],
       [0.75800885, 0.71157722, 0.11065339]])

In [5]:
np.random.randn(5)

array([ 0.88096689,  0.72701789, -0.80967546, -0.93241828,  0.09128288])

In [6]:
np.random.randn(5, 3)

array([[ 1.03087812,  0.05853294, -1.06342715],
       [-0.81388337,  0.43685044,  1.51142546],
       [ 0.89784596,  0.15110246,  1.10666145],
       [ 0.46711734, -1.01583482, -0.92854102],
       [-0.25620688, -0.96676858, -0.32111352]])

In [7]:
#numeros aleatorios enteros
np.random.randint(1,20)

16

In [8]:
np.random.randint(1,20)

3

In [9]:
np.random.randint(1,20,6)

array([16, 18, 11,  5, 11,  8])

In [10]:
#Valors posicion, maximo y minimos de un array despues de un random
array = np.random.randint(1,20,50)

In [11]:
array

array([ 1, 10, 14,  7,  5, 16,  7,  4,  1,  8,  3,  4,  9, 10, 12,  5,  7,
        1,  4, 17,  1,  3,  3,  8,  3,  9,  9, 13, 14,  2, 11,  8,  5, 13,
       13, 19,  8,  5, 15, 14, 14, 18, 17,  5, 10, 17, 16,  3,  6, 11])

In [14]:
val_max = array.max()

In [15]:
val_max

19

In [16]:
posi_val_max = array.argmax()

In [17]:
posi_val_max

35

In [18]:
val_min = array.min()

In [19]:
val_min

1

In [21]:
posi_val_min = array.argmin()

In [22]:
posi_val_min

0

In [23]:
#Indexar array

In [24]:
array = np.arange(0,10)

In [25]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
array[0]

0

In [27]:
array[3:5]

array([3, 4])

In [28]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array[5:]

array([5, 6, 7, 8, 9])

In [30]:
array[:4]

array([0, 1, 2, 3])

In [31]:
#Generar una copia de una arreglo 

array2 = array.copy()

In [32]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#Indexar array 2 o mas dimensiones
array = np.array([[1,2,3],[6,5,4],[9,8,7]])

In [35]:
array

array([[1, 2, 3],
       [6, 5, 4],
       [9, 8, 7]])

In [36]:
array[1]

array([6, 5, 4])

In [37]:
array[:2]

array([[1, 2, 3],
       [6, 5, 4]])

In [38]:
array[0][0]

1

In [42]:
array[:,0][:]

array([1, 6, 9])

In [43]:
#Seleccionar elementos de un array con condición

array = np.arange(0,10)

In [44]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
condicion  = array > 4

In [46]:
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
array[condicion]

array([5, 6, 7, 8, 9])

In [48]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
array[array % 2 ==0]

array([0, 2, 4, 6, 8])

In [53]:
#Operaciones sobre los arrays
array = np.arange(1,20)


In [54]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
array + array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [56]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
array * 2


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [58]:
array + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24])

In [59]:
np.max(array)

19