# Punto1

In [40]:
#A.Crea una lista “materias” con los textos(materias) llamadas “programación, IOT, calidad”
materias = ['programacion', 'IOT', 'calidad']
print(materias)

#B.Crea una lista “notas” con los valores para cada asignatura “4.5 , 3.8 , 4.4” respectivamente
notas = ['4.5', '3.8', '4.4']
print(notas)

['programacion', 'IOT', 'calidad']
['4.5', '3.8', '4.4']


In [98]:
valores = pd.DataFrame(notas,materias)
valores.head()

0
programacion  4.5
IOT           3.8
calidad       4.4

In [96]:
#C.Crea una lista donde las notas sean los valores y las materias sean los índices.

import pandas as pd
listadodenotas = pd.Series(notas,index = materias)
listadodenotas

programacion    4.5
IOT             3.8
calidad         4.4
dtype: object

In [104]:
#D.Crear una materia llamada “nota_IOT” la cual se le asignara la nota de IOT
s.append(pd.Series(3.8, index=['nota_IOT']))

programacion    4.5
IOT             3.8
calidad         4.4
nota_IOT        3.8
dtype: object

# Punto2

In [59]:
#A.Crear un dataframe  con las ventas de 3 sucursales para los meses de marzo, abril y mayo
import pandas as pd
import numpy as np
datos = {'Mes':['Marzo','Abril','Mayo'], 'Ventas':[30500, 35600, 28300]}
contabilidad = pd.DataFrame(datos)
print(contabilidad)

     Mes  Ventas
0  Marzo   30500
1  Abril   35600
2   Mayo   28300


In [62]:
#B.Crear una variable “venta_marzo” que contenga una lista de 3 números enteres aleatorios entre 201 y 500
venta_marzo = np.random.randint(201,500,3)
venta_marzo

array([230, 475, 268])

In [63]:
#C.Crear una variable “venta_abril” que contenga una lista de 3 números enteres aleatorios entre 201 y 500
venta_abril = np.random.randint(201,500,3)
venta_abril

array([208, 488, 498])

In [64]:
#D.Crear una variable “venta_mayo” que contenga una lista de 3 números enteres aleatorios entre 201 y 500
venta_mayo = np.random.randint(201,500,3)
venta_mayo

array([217, 294, 439])

In [66]:
#E.Crear una variable “fila” que contenga una lista con las palabras: venta_marzo, venta_abril, venta_mayo”
fila = ["venta_marzo", "venta_abril", "venta_mayo"]
fila

['venta_marzo', 'venta_abril', 'venta_mayo']

In [68]:
#F.Crear una variable “columna” que contenga una lista con las palabras: sede1, sede2, sede3”

columna = ["sede1",
           "sede2",
           "sede3"]
print(columna)

['sede1', 'sede2', 'sede3']


In [76]:
#G.Crear una variable “ventas” que contenga una lista con los valores de ventas de marzo, abril y mayo
Ventas = [30500, 35600, 28300]
Ventas

[30500, 35600, 28300]

In [77]:
#H.Crear una varible “dataframe” que contenga las ventas, filas y columnas
datos = pd.DataFrame(Ventas)
datos.head()

0
0  30500
1  35600
2  28300

In [110]:
#I.Imprimir las ventas mes a mes por sede
datos = pd.DataFrame([venta_marzo,venta_abril,venta_mayo], index = ['Marzo','Abril','Mayo'],columns = ['SEDE1','SEDE2','SEDE3'])
datos

SEDE1  SEDE2  SEDE3
Marzo    230    475    268
Abril    208    488    498
Mayo     217    294    439