# 2.Realice un ejemplo de listas en Python (0.5)

In [9]:
lista = [1, 2, 3, 4]

In [10]:
lista

[1, 2, 3, 4]

In [18]:
lista2 = [1, 2.5, 'DevCode', [5,6] ,4]

In [19]:
lista2

[[0, 0, 0], [0, 0, 0]]

In [21]:
for element in lista:
    print (element)

1
2.5
DevCode
[5, 6]
4


# 3.Realice un ejemplo de range en Python (0.5)

In [13]:
import numpy as np

In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 5.Cargue en una lista 8 posiciones con edades diferentes y al momento de recorrer la lista determinar mediante una función llamada mayor(edad) cual es mayor de 18 y cual no (1.0)



In [56]:
edad = np.random.randint(0,20,10)
print(edad)

[15 17 12 11  8 12 19  6 15 18]


In [62]:
def mayor(edad):
    mayores=[]
    menores=[]
    for W in edad:
        if W >=18:
            mayores.append(W)
        else:
            menores.append(W)      
    print("los menores son",menores)
    print("los mayores son",mayores)
    print("QUE TENGAS UN BUEN DIA!!")
    
mayor(edad)

los menores son [15, 17, 12, 11, 8, 12, 6, 15]
los mayores son [19, 18]
QUE TENGAS UN BUEN DIA!!


# 7.Cargar dos listas (ListA - ListB) de forma aleatoria y en una tercer lista (ListC) obtener la sumatoria (ListC = ListA + ListB) (1.0)

In [ ]:
import numpy as np

In [30]:
ListadoA = np.random.randint(0,20,39)
ListadoB = np.random.randint(0,50,39)
listadoC = list(A+B for (A,B)in zip(ListadoA,ListadoB)) #La función zip () devuelve un objeto zip, que es un iterador de tuplas donde el primer elemento en cada iterador pasado se empareja, y luego el segundo elemento en cada iterador pasado se empareja, etc.

In [31]:
ListadoA

array([15, 12,  5, 17,  1,  4, 12, 19,  2, 16, 10,  1,  0,  8, 16,  6,  2,
       12, 13,  2,  9,  7, 11, 12, 11,  0, 15, 17, 16,  7,  1, 17, 14,  1,
       11,  0,  7, 18, 18])

In [32]:
ListadoB

array([29, 30, 45, 46, 10, 31, 31, 31,  0, 30,  5,  6, 13, 29, 20, 47, 35,
       25,  3, 10, 46, 49, 48, 11, 41,  8, 17, 11, 23, 33, 12, 28,  5, 12,
       29, 31, 28, 38,  0])

In [33]:
listadoC #SUMATORIA DE VALORES

[44,
 42,
 50,
 63,
 11,
 35,
 43,
 50,
 2,
 46,
 15,
 7,
 13,
 37,
 36,
 53,
 37,
 37,
 16,
 12,
 55,
 56,
 59,
 23,
 52,
 8,
 32,
 28,
 39,
 40,
 13,
 45,
 19,
 13,
 40,
 31,
 35,
 56,
 18]

In [34]:
array.max()#valor maximo

38

In [35]:
array.min() #valor minimo

4

In [36]:
array.argmax() #posicion

17

In [37]:
condicion = array > 3

In [38]:
condicion

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [39]:
array[condicion]

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])