#3.Crear una lista de números secuenciales que tenga como rango de valor mínimo 10 y máximo 39, convertir esta lista en una lista o matriz de dos (2) dimensiones ( 3 filas por 10 columnas) y generar en pantalla (imprimir) el valor del elemento de la esquina superior derecha de la matriz.(2.0)

In [7]:
import numpy as np #importancion de libreria

In [37]:
N = np.arange(10,40) #rangos de 10 a 40

In [38]:
N

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [41]:
X = np.array(N).reshape(3,10) #matriz de 3x10

In [42]:
X

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [32]:
X[0,9] #el valor del elemento de la esquina superior derecha de la matriz

19

In [20]:
condicion = X > 3

In [21]:
condicion

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

# Forma2

In [45]:
import numpy as np

a = list(range(10, 40))
b = np.array(a)
x = np.reshape(b, (3, 10))

print(x)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [44]:
x[0,9]

19

In [46]:
condicion = X > 3

In [47]:
condicion

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])


#4.Crear un array de una dimensión con 9 valores aleatorios todos enteros que estén entre 0 y 100.Convierte este array en una matriz de 2 dimensiones (3 filas y 3 columnas).Generar en pantalla (Imprimir) el valor del elemento de la matriz de la esquina inferior derecha. (2.0)


In [5]:
import numpy as np

x=np.random.randint(100, size=9)
a = np.reshape(x, (3, 3))
print(a)

[[28 86 83]
 [14 49 29]
 [28 47 68]]


In [23]:
a[2,2]

68

In [24]:
condicion = a > 3

In [25]:
condicion

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])